In app purchases flow
PickMeSA/mobile.flutter.pickme pull request #124
Opened 2024-03-25 18:59 UTC by andrewdvt

2024-03-25 21:52 UTC, sergembamba requested changes

2024-03-25 21:52 UTC, sergembamba commented on ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
Please do not commit this, it was only for development purpose

2024-03-25 21:52 UTC, sergembamba commented on test/in_app_purchases/in_app_purchase_service_test.dart
> +    // test('activate should return expected response entity on successful response', () async {
Please do not commit commented code

2024-03-25 21:52 UTC, sergembamba commented on lib/shared/services/remote/api_service/in_app_purchases/in_app_purchases_service_impl.dart
> +      UserModel userModel = boxUser.get(current);
All this logic, belongs to the usecase, the service should just receive the request DTO

2024-03-25 21:52 UTC, sergembamba commented on lib/shared/in_app_purchases/presentation/in_app_purchase_bloc.dart
> +       await activatePurchaseUseCase.call(
You need to get the result here and use it in the whenComplete bloc

2024-03-25 21:52 UTC, sergembamba commented on lib/features/final_details/presentation/final_details_page.dart
> +  Future<void> showConfirmationDialog(BuildContext context) async {
I believe this method should be private

2024-03-25 21:52 UTC, sergembamba commented on lib/features/final_details/domain/usecases/activate_purchase_use_case.dart
> +      rethrow;
Catching and rethowing without any extra operation is equivalent to not having the try/catch bloc

2024-03-25 21:52 UTC, sergembamba commented on lib/features/final_details/domain/usecases/activate_purchase_use_case.dart
> +      return await _inAppPurchasesService.activate(params!.purchaseDetails);
Please do not force unwrap; if the parameters are required, then make them non optional in the method signature.

2024-03-25 21:52 UTC, sergembamba commented on lib/core/PickMeApp.dart
> +    await dotenv.load(fileName: ".env");
Please surround this with a try/catch and adequate log; by default, developers would not have a .env file

2024-03-25 21:52 UTC, sergembamba commented on ios/Runner.xcodeproj/project.pbxproj
Do not commit anything in the ios folder

2024-03-25 21:52 UTC, sergembamba commented on README.md
> +
also add the note regarding the salt

2024-03-26 10:18 UTC, andrewdvt commented on lib/features/final_details/domain/usecases/activate_purchase_use_case.dart
> +      return await _inAppPurchasesService.activate(params!.purchaseDetails);
the Params object is being used in too many places and changing it would be require a good amount of impact assessment

2024-03-26 10:24 UTC, andrewdvt commented
@sergembamba I have updated the code here. May you please take a look and let me know if I need to change anything

2024-03-26 11:38 UTC, sergembamba approved these changes

2024-03-26 11:41 UTC, sergembamba approved these changes

2024-03-26 11:43 UTC, merged